### PR TITLE
Ignore blank messages & send to multiple channels

### PR DESCRIPTION
**Pull request by brunomgalmeida**
ignore blank messages so that things like
```sh
echo "" | slacktee ...
```
dont send anything.

### CODE REVIEW

**Comment by Chikashi-Kato** [comment]
Thank you for the pull request!

I'm reviewing your changes, but I have a question with the change supporting multiple channels.
Does your change work with the streaming option? The implementation is complicated and I'd like to make sure it's still working with multi-channels. 

BTW, since `slacktee` passes through STDIN to STDOUT, you can send the same messages to multiple channels by chaining `slacktee`. For example if you want to send a message to `channel-a` and `channel-b`, your command can be `echo 'test' | slacktee -c channel-a | slacktee -c channel-b`.

**Comment by brunomgalmeida** [comment]
thanks for you comment, indeed streaming was broken. I have fixed it.
We use slacktee with mutiple flags, example
```sh
( ... ) 
| slacktee -q -a "warning" -c "$SLACK_CHANNEL" -s "JIRA" "https://jira.com/browse/" -s "URI" "$h" -s "Runbook" "$link/#account-statements" -t "Something is not right here"
```
To pipe again, we would have to duplicate all the extra flag and/or we could manage these with variables...

If you dont think this PR is relevant or add unnecessary complexity, please feel free to reject.

**Comment by brunomgalmeida** [comment]
To test streaming to mutiple channel, you can do something like

```sh
{ while true; do echo "$( date )" >> a; sleep 1; done } &

tail -f a | ./slacktee -c '@chan1' -c '#chan2' --streaming --streaming-batch-time 5 --debug
```

**Comment by Chikashi-Kato** [comment]
> To pipe again, we would have to duplicate all the extra flag and/or we could manage these with variables...

Makes sense! Yes, I believe supporting multiple channels works well for the use case you have posted above!

I have reviewed your code and test the changes on my end.
Since the associative array is not supported in the old version of `bash`, I reimplement it with a regular array. 
Also, I have modified the document of `-c` option a bit and added a few test cases.

Unfortunately, the change ignoring blank messages didn't work on my end and I couldn't make it work. In order to merge your rest of changes, I had to remove it from your PR.

It would be great if you can open another PR for ignoring the empty input with `-t` option!
Thank you for your contribution @brunomgalmeida ! I'm pretty sure many people love the new feature!

**Pull request merged**
